version: "3.1"
services:
  server:
    image: cs16-server:$IMAGE_TAG
    build:
      context: .
      dockerfile: image/Dockerfile
      args:
        - steam_user=${STEAM_USER:-anonymous}
        - steam_password=${STEAM_PASSWORD:-''}
        - amxmod_version=1.8.2
    environment:
      - SERVER_NAME=${SERVER_NAME:-CS 1.6 Server}
      - START_MAP=${START_MAP:-de_dust2}
      - MAXPLAYERS=${MAXPLAYERS:-32}
      - ADMIN_IP
      - ADMIN_NAME
      - ADMIN_PASSWORD
      - SERVER_PASSWORD
      - YAPB_ENABLED
      - YAPB_PASSWORD
      - CSDM_MODE
      - STEAM_ID
    ports:
      - "27015:27015/udp"
