version: "3.1"
services:
  server:
    image: cs16docker:$IMAGE_TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - steam_user=$STEAM_USER
        - steam_password=$STEAM_PASSWORD
        - amxmod_version=1.8.2
    volumes:
      - ./mod/yapb:/opt/hlds/cstrike/addons/yapb:rw
      - ./files/plugins.ini:/opt/hlds/cstrike/addons/metamod/plugins.ini:rw
      - ./files/server.cfg:/opt/hlds/cstrike/server.cfg
      - ./files/amxx_yapbmenu.sma:/opt/hlds/cstrike/addons/amxmodx/scripting/amxx_yapbmenu.sma
      - ./files/amxx_yapbmenu.amxx:/opt/hlds/cstrike/addons/amxmodx/plugins/amxx_yapbmenu.amxx
      - ./files/amx_plugins.ini:/opt/hlds/cstrike/addons/amxmodx/configs/plugins.ini
    environment:
      - START_MAP=${START_MAP:-de_dust2}
      - ADMIN_STEAM=${ADMIN_STEAM:-0:1:1234566}
      - SERVER_NAME=${SERVER_NAME:-CS 1.6 Server}
      - MAXPLAYERS=${MAXPLAYERS:-32}
    restart: always
    ports:
      - "27015:27015/udp"