version: "3.1"
services:
  server:
    image: cs16-server:$IMAGE_TAG
    build:
      context: .
      dockerfile: image/cs16-server/Dockerfile
#    volumes:
#      - ./config/server.cfg:/opt/hlds/cstrike/server.cfg
#      - ./config/maps.ini:/opt/hlds/cstrike/addons/amxmodx/configs/maps.ini
#      - ./hlds_run.sh:/bin/hlds_run.sh
    environment:
      - SERVER_NAME=${SERVER_NAME:-CS 1.6 Server}
      - START_MAP=${START_MAP:-de_dust2}
      - MAXPLAYERS=${MAXPLAYERS:-32}
      - ADMIN_STEAM
      - ADMIN_IP
      - ADMIN_NAME
      - ADMIN_PASSWORD
      - SERVER_PASSWORD
      - YAPB_ENABLED
      - YAPB_PASSWORD
    restart: always
    ports:
      - "27015:27015/udp"