maps/fy_snow.res 
sound/misc/comeagain.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/woohoo2.wav
sound/misc/dohoo.wav
sound/misc/dohnuts.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh4.wav
sound/misc/doh5.wav
sound/misc/doh7.wav
sound/misc/monsterkill.wav 
sound/misc/multikill.wav 
sound/misc/ultrakill.wav 
sound/misc/killingspree.wav 
sound/misc/humiliation.wav 
sound/misc/headshot.wav 
sound/misc/doublekill.wav 
sound/misc/firstblood.wav 
sound/misc/rampage.wav 
sound/misc/unstoppable.wav 
sound/misc/dominating.wav 
sound/misc/perfect.wav 
sound/misc/godlike.wav 
sound/misc/prepare.wav 